name: Release

on:
  push:
    branches:
      - master
      - main

      - name: Debug
  run: |
    ls -la
    cat package.json

jobs:
  release:
    uses: finsweet/workflow-release/.github/workflows/release.yml@main
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
